 const types = {
     ALL_ITEMS: 'ALL_ITEMS',
     ADD_FAV: 'ADD_FAV',
     ADD_DETAIL: 'ADD_DETAIL',
     GET_CONTACT_MESSAGE: 'GET_CONTACT_MESSAGE',
     ADD_TO_SHOPPING: 'ADD_TO_SHOPPING',
     TOGGLE_TOAST: 'TOGGLE_TOAST',
     INCREASE_QUANTITY:'INCREASE_QUANTITY',
     DECREASE_QUANTITY: 'DECREASE_QUANTITY',
     
     
}
export default types;